name: gpstracker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

  golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-go@v3
          with:
            go-version: 1.20

        - uses: actions/checkout@v3

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.51.1